import { useState } from 'react';
import { twMerge } from 'tailwind-merge';

interface MfaVerifyProps {
  onVerify: (code: string) => void;
  onCancel: () => void;
}

export function MfaVerify({ onVerify, onCancel }: MfaVerifyProps) {
  const [code, setCode] = useState('');
  
  return (
    <div className="p-6 rounded-3xl bg-[#131C33] border border-white/10 mb-5 flex flex-col gap-4">
      <h3 className="text-lg font-bold text-center text-white">Multi-Factor Authentication</h3>
      <p className="text-sm text-center text-white/60 leading-relaxed">
        Please enter the security verification code sent to your device or generated by your authenticator app
      </p>
      
      <input
        className="h-14 rounded-xl border border-white/10 bg-white/5 text-center text-xl font-bold tracking-[0.25em] text-white placeholder-white/40 focus:outline-none focus:border-blue-500 transition-colors"
        value={code}
        onChange={(e) => {
          const val = e.target.value.replace(/[^0-9]/g, '');
          if (val.length <= 6) setCode(val);
        }}
        placeholder="Enter 6-digit code"
        autoFocus
      />
      
      <div className="flex flex-row gap-3 mt-2">
        <button
          onClick={() => onVerify(code)}
          disabled={code.length < 6}
          className={twMerge(
            "flex-1 h-[50px] rounded-xl font-bold flex items-center justify-center transition-opacity",
            code.length < 6 
              ? "bg-blue-600/50 text-white/50 cursor-not-allowed" 
              : "bg-blue-600 hover:bg-blue-500 text-white cursor-pointer"
          )}
        >
          Verify OTP
        </button>
        <button
          onClick={onCancel}
          className="h-[50px] rounded-xl border border-white/10 flex items-center justify-center px-5 text-white font-semibold hover:bg-white/5 transition-colors cursor-pointer"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
