import React, { useState } from 'react';
import { View, Text, StyleSheet, TextInput, Pressable } from 'react-native';
import { useColors } from '@/hooks/use-colors';
import { GradientButton } from './gradient-button';

interface MfaVerifyProps {
  onVerify: (code: string) => void;
  onCancel: () => void;
}

export function MfaVerify({ onVerify, onCancel }: MfaVerifyProps) {
  const colors = useColors();
  const [code, setCode] = useState('');
  
  return (
    <View style={styles.container}>
      <Text style={[styles.title, { color: colors.foreground }]}>Multi-Factor Authentication</Text>
      <Text style={[styles.subtitle, { color: colors.muted }]}>
        Please enter the security verification code sent to your device or generated by your authenticator app
      </Text>
      
      <TextInput
        style={[
          styles.input,
          { 
            color: colors.foreground,
            borderColor: colors.border,
            backgroundColor: 'rgba(255, 255, 255, 0.03)'
          }
        ]}
        value={code}
        onChangeText={setCode}
        placeholder="Enter 6-digit code"
        placeholderTextColor={colors.muted}
        keyboardType="number-pad"
        maxLength={6}
        autoFocus
      />
      
      <View style={styles.buttonContainer}>
        <GradientButton
          onPress={() => onVerify(code)}
          style={{ flex: 1 }}
          disabled={code.length < 6}
        >
          Verify OTP
        </GradientButton>
        <Pressable 
          onPress={onCancel}
          style={[styles.cancelButton, { borderColor: colors.border }]}
        >
          <Text style={{ color: colors.foreground, fontWeight: '600' }}>Cancel</Text>
        </Pressable>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 24,
    borderRadius: 24,
    backgroundColor: '#131C33',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 20,
    gap: 16,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
  },
  subtitle: {
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 18,
  },
  input: {
    height: 54,
    borderRadius: 14,
    borderWidth: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: 4,
  },
  buttonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  cancelButton: {
    height: 50,
    borderRadius: 14,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
});
